# Generated by Django 2.2.4 on 2019-08-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=25)),
                ('card_number', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=10)),
                ('card_bank', models.CharField(max_length=50)),
                ('processing_charges', models.CharField(max_length=50)),
            ],
        ),
    ]
