# Generated by Django 2.0 on 2019-08-08 15:45

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('card_holder_name', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=25)),
                ('card_number', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=10)),
                ('card_bank', models.CharField(max_length=50)),
            ],
        ),
    ]
