# Generated by Django 2.0 on 2019-08-08 15:45

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('wallet_name', models.CharField(max_length=50)),
                ('wallet_auth_id', models.CharField(max_length=25)),
                ('wallet_processing_charges', models.CharField(max_length=50)),
            ],
        ),
    ]
