# Generated by Django 2.2.4 on 2019-08-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=50)),
                ('wallet_auth_id', models.CharField(max_length=25)),
                ('wallet_processing_charges', models.CharField(max_length=50)),
            ],
        ),
    ]
