# Generated by Django 2.2.4 on 2019-08-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('sender_type', models.CharField(choices=[('user', 'USER'), ('bot', 'BOT')], default='bot', max_length=50)),
                ('message_content', models.TextField()),
                ('message_type', models.CharField(choices=[('information', 'INFORMATION'), ('option', 'OPTION'), ('null', 'NULL')], default='null', max_length=50)),
                ('time_stamp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.CharField(max_length=100)),
                ('solutions', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('info', 'INFO'), ('option', 'OPTION')], default='option', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=100)),
                ('ticket_issue_date', models.CharField(max_length=100)),
                ('ticket_resolution_proposed_date', models.CharField(max_length=100)),
                ('ticket_resolved_date', models.CharField(blank=True, max_length=100)),
                ('ticket_details', models.CharField(blank=True, max_length=1000)),
                ('ticket_resolution_response', models.CharField(blank=True, max_length=100)),
                ('ticket_re_action_reason', models.CharField(blank=True, max_length=100)),
                ('ticket_status', models.CharField(choices=[('Open', 'OPEN'), ('Closed', 'CLOSED')], default='Open', max_length=50)),
                ('transactions_linked', models.CharField(blank=True, max_length=100)),
                ('chat_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
