# Generated by Django 2.2.4 on 2019-08-11 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatsupport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.CharField(max_length=100)),
                ('solutions', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('info', 'INFO'), ('option', 'OPTION')], default='option', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=100)),
                ('ticket_issue_date', models.CharField(max_length=100)),
                ('ticket_resolution_proposed_date', models.CharField(max_length=100)),
                ('ticket_resolved_date', models.CharField(max_length=100)),
                ('ticket_resolution_response', models.CharField(max_length=100)),
                ('ticket_re_action_reason', models.CharField(max_length=100)),
                ('ticket_status', models.CharField(choices=[('Open', 'OPEN'), ('Closed', 'CLOSED')], default='Open', max_length=50)),
                ('chat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'USER'), ('bot', 'BOT')], default='bot', max_length=50)),
                ('message_content', models.TextField()),
                ('message_type', models.CharField(choices=[('information', 'INFORMATION'), ('option', 'OPTION'), ('null', 'NULL')], default='null', max_length=50)),
                ('time_stamp', models.CharField(max_length=50)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatsupport.Chat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
