# Generated by Django 2.2.4 on 2019-08-06 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatsupport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=100)),
                ('ticket_issue_date', models.DateTimeField()),
                ('ticket_resolution_proposed_date', models.DateTimeField()),
                ('ticket_resolved_date', models.DateTimeField()),
                ('ticket_resolution_response', models.TextField()),
                ('ticket_re_action_reason', models.TextField()),
                ('ticket_status', models.CharField(max_length=50)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatsupport.Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_time', models.DateTimeField()),
                ('receive_time', models.DateTimeField()),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatsupport.Chat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
