# Generated by Django 2.2.4 on 2019-08-06 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatsupport', '0002_chat_messages_problems_ticket'),
    ]

    operations = [
    ]
