# Generated by Django 2.2.4 on 2019-08-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsupport', '0002_chat_messages_problems_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
