# Generated by Django 2.2.4 on 2019-08-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsupport', '0003_auto_20190806_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='problem',
            new_name='problems',
        ),
        migrations.RenameField(
            model_name='problems',
            old_name='solution',
            new_name='solutions',
        ),
        migrations.AddField(
            model_name='problems',
            name='type',
            field=models.CharField(choices=[('info', 'INFO'), ('option', 'OPTION')], default='option', max_length=10),
        ),
    ]
