# Generated by Django 2.2.4 on 2019-08-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsupport', '0004_auto_20190806_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='chat',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_issue_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_resolution_proposed_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_resolved_date',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
