# Generated by Django 2.2.4 on 2019-08-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsupport', '0005_auto_20190808_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='chat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_re_action_reason',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_resolution_response',
            field=models.CharField(max_length=100),
        ),
    ]
