# Generated by Django 2.2.4 on 2019-08-09 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatsupport', '0006_auto_20190809_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
