# Generated by Django 2.2.4 on 2019-08-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsupport', '0007_remove_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('info', 'INFO'), ('option', 'OPTION')], default='Open', max_length=50),
        ),
    ]
