# Generated by Django 2.0 on 2019-08-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsupport', '0008_auto_20190809_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Open', 'OPEN'), ('Closed', 'CLOSED')], default='Open', max_length=50),
        ),
    ]
