# Generated by Django 2.0 on 2019-08-08 15:45

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('transaction_amount', models.IntegerField()),
                ('transaction_date_time', models.DateTimeField()),
                ('transaction_state', models.CharField(max_length=50)),
                ('card_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card')),
                ('wallet_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Wallet')),
            ],
        ),
    ]
