# Generated by Django 2.2.4 on 2019-08-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        ('card', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.IntegerField()),
                ('transaction_date_time', models.CharField(max_length=100)),
                ('transaction_state', models.CharField(choices=[('Failed', 'Failed'), ('Success', 'Success')], default='Success', max_length=50)),
                ('payment_mode', models.CharField(choices=[('Net Banking', 'Net Banking'), ('Card', 'Card'), ('Wallet', 'Wallet')], default='Net Banking', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('refund_status', models.BooleanField()),
                ('ticket_status', models.BooleanField()),
                ('card_linked', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='card.Card')),
                ('wallet_linked', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Wallet')),
            ],
        ),
    ]
