# Generated by Django 2.2.4 on 2019-08-06 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mobile_number', models.CharField(max_length=10)),
                ('current_network', models.CharField(max_length=100)),
                ('upc', models.CharField(max_length=100)),
                ('requested_date_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 6, 15, 5, 52, 225108))),
                ('status', models.CharField(max_length=100)),
                ('circle', models.CharField(max_length=100)),
            ],
        ),
    ]
