# Generated by Django 2.0 on 2019-08-08 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newconnection', '0002_auto_20190806_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mobile_number', models.CharField(max_length=10)),
                ('current_network', models.CharField(max_length=100)),
                ('upc', models.CharField(max_length=100)),
                ('requested_date_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 9, 4, 57, 51, 417379))),
                ('status', models.CharField(max_length=100)),
                ('circle', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Portin',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='state',
            new_name='circle',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='zipcode',
            new_name='status',
        ),
    ]
