# Generated by Django 2.0 on 2019-08-09 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newconnection', '0004_auto_20190809_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porting',
            name='requested_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 9, 11, 25, 20, 985225)),
        ),
    ]
