# Generated by Django 2.2.4 on 2019-08-12 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newconnection', '0023_auto_20190812_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porting',
            name='requested_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 21, 27, 40, 132144)),
        ),
    ]
