# Generated by Django 2.2.4 on 2019-08-13 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newconnection', '0024_auto_20190812_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porting',
            name='requested_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 7, 28, 9, 286347)),
        ),
    ]
