# Generated by Django 2.0 on 2019-08-08 23:28

from django.db import migrations, models
import djongo.models.fields
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('expiry', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('subscriber_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('primary_phone_no', models.IntegerField()),
                ('alternate_phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('circle', models.CharField(max_length=100)),
                ('payment_info', djongo.models.fields.EmbeddedModelField(model_container=registration.models.PaymentInfo, model_form_class=registration.models.PaymentInfoForm, null=True)),
                ('proofs_attached', models.ImageField(default='ID.jpg', upload_to='proofs')),
            ],
        ),
    ]
